# Generated by Django 5.0.6 on 2024-05-29 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_wishlistedby_alter_listing_activestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlistedBy',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
