# Generated by Django 5.0.6 on 2024-05-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category_remove_listing_wishlistedby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
